import { expect, test, type Page } from '@playwright/test';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Vec3, YardMap } from '../../src/domain/model';
import { GA01_TARGETS, readGA01Target } from '../helpers/GA01_targets';
import { openDrawingSettings } from '../helpers/workbenchUi';
import { readyWorkbench, importMapUI, browserSaved, storedWorkspace, checkpoint, expectVisiblePosition } from '../helpers/RF01_workbench';

test.use({ viewport: { width: 1920, height: 1080 } });
async function current(page: Page): Promise<YardMap> {
  await browserSaved(page);
  await expect.poll(async () => (await storedWorkspace(page)).record?.draft?.contentHash).toBe(await page.getByTestId('map-hash').textContent());
  return JSON.parse((await storedWorkspace(page)).record!.draft!.mapJson) as YardMap;
}
async function click(page: Page, point: Vec3) { const p = await expectVisiblePosition(page, point); await page.mouse.click(p.x, p.y); }

test('real CIMC continuous entrances snap to slanted edges and preserve each click through history and saving', async ({ page, browser }, info) => {
  test.setTimeout(150000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const original = await readGA01Target(GA01_TARGETS.find(target => target.id === 'cimc_v02')!);
  const map = structuredClone(original); map.mapId = 'MAP_CIMC_CONTINUOUS_ENTRANCES'; map.metadata.name = 'CIMC 真实底图连续入口验收副本';
  for (const key of ['nodes', 'roads', 'junctions', 'movements', 'facilities', 'zones', 'accessPoints', 'servicePoints', 'resources', 'extensions', 'extensionNamespaces', 'assets', 'backgroundLayers'] as const) (map as unknown as Record<string, unknown>)[key] = {};
  const imagePath = resolve('.cache/BG01/calibrated-cimc/background.jpg');
  const imageSHA = createHash('sha256').update(await readFile(imagePath)).digest('hex');
  expect(imageSHA).toBe('8ec6e74a72c9757f7113a440832dc9d9166518fe7f9da75979629a2cdb2ef713');
  await readyWorkbench(page); await importMapUI(page, map);
  await page.getByRole('button', { name: '底图', exact: true }).click();
  await page.getByTestId('background-file-input').setInputFiles([imagePath, resolve('.cache/BG01/calibrated-cimc/calibration.json')]);
  await expect(page.getByTestId('background-calibration-status')).toContainText('校准匹配');
  await page.getByRole('button', { name: '添加此底图', exact: true }).click();
  await expect(page.getByTestId('background-render-state')).toHaveAttribute('data-loaded', '1');
  await page.getByRole('button', { name: '适应底图', exact: true }).click();
  await page.locator('summary').filter({ hasText: /^底图显示与调整$/ }).click();
  await page.getByRole('button', { name: '收起属性面板', exact: true }).click();
  await page.getByLabel('建筑绘制形状', { exact: true }).selectOption('facilityOrientedRect');
  await page.getByRole('button', { name: '保留原图并升级', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await click(page, [360, 1020, 0]); await click(page, [450, 1050, 0]); await click(page, [420, 1090, 0]);
  const first = await current(page), facilityId = Object.keys(first.facilities)[0]!;
  await page.getByLabel('建筑绘制形状', { exact: true }).selectOption('facilityRect');
  await click(page, [500, 1020, 0]); await click(page, [550, 1070, 0]);
  const base = await current(page), secondId = Object.keys(base.facilities).find(id => id !== facilityId)!;
  await page.getByRole('button', { name: '选择', exact: true }).click();
  await page.getByTestId('facilities-item-' + facilityId).click();
  await page.getByRole('button', { name: '添加入口', exact: true }).last().click();
  const panel = page.getByRole('complementary', { name: '连续添加入口', exact: true });
  await expect(panel).toBeVisible(); await expect(panel).toContainText('所属建筑：' + base.facilities[facilityId]!.name);
  await expect(panel).toContainText('当前入口数：0'); await expect(page.getByRole('dialog')).toHaveCount(0);
  const ring = base.facilities[facilityId]!.boundary.outer;
  const center: Vec3 = [(ring[0][0] + ring[2][0]) / 2, (ring[0][1] + ring[2][1]) / 2, 0];
  await click(page, center); expect(await current(page)).toEqual(base); await expect(panel).toBeVisible();
  let previous = base;
  const positions: Vec3[] = [];
  for (let index = 0; index < 3; index++) {
    const a = ring[index]!, b = ring[index + 1]!, dx = b[0] - a[0], dy = b[1] - a[1], length = Math.hypot(dx, dy);
    const midpoint: Vec3 = [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2, 0], at = await expectVisiblePosition(page, midpoint);
    // The outer ring is counterclockwise; move four CSS pixels to its exterior side.
    const x = at.x + 4 * dy / length, y = at.y + 4 * dx / length;
    await page.mouse.move(x, y);
    if (index === 1) await page.mouse.dblclick(x, y); else await page.mouse.click(x, y);
    await expect(page.getByRole('dialog')).toHaveCount(0); await expect(panel).toBeVisible();
    await expect(panel).toContainText('当前入口数：' + (index + 1));
    const next = await current(page), id = Object.keys(next.accessPoints).find(id => !previous.accessPoints[id])!, access = next.accessPoints[id]!;
    expect(Object.keys(next.accessPoints)).toHaveLength(index + 1); expect(Object.keys(next.nodes)).toHaveLength(index + 1);
    expect(access.name).toBe('入口' + String(index + 1).padStart(3, '0')); expect(access.facilityId).toBe(facilityId);
    const position = next.nodes[access.nodeId]!.position; positions.push(position);
    expect(Math.abs((position[0] - a[0]) * dy - (position[1] - a[1]) * dx) / length).toBeLessThan(1e-7);
    expect(Math.hypot(position[0] - midpoint[0], position[1] - midpoint[1])).toBeLessThanOrEqual(2 / at.scale);
    expect(next.roads).toEqual(base.roads); expect(next.facilities[facilityId]!.boundary).toEqual(base.facilities[facilityId]!.boundary);
    expect(next.facilities[secondId]).toEqual(base.facilities[secondId]); expect(next.servicePoints).toEqual(base.servicePoints); expect(next.resources).toEqual(base.resources);
    for (const [nodeId, node] of Object.entries(previous.nodes)) expect(next.nodes[nodeId]).toEqual(node);
    expect(next.revision).toBe(previous.revision + 1);
    await page.getByRole('button', { name: '撤销', exact: true }).click(); expect(await current(page)).toEqual(previous); await expect(panel).toBeVisible();
    await expect(panel).toContainText('当前入口数：' + index);
    await page.getByRole('button', { name: '重做', exact: true }).click(); expect(await current(page)).toEqual(next); await expect(panel).toBeVisible();
    previous = next;
  }
  expect(new Set(Object.values(previous.accessPoints).map(point => point.nodeId)).size).toBe(3);
  expect(new Set(previous.facilities[facilityId]!.accessPointIds)).toEqual(new Set(Object.keys(previous.accessPoints)));
  await click(page, positions[0]!); expect(await current(page)).toEqual(previous); await expect(panel).toContainText('当前入口数：3');
  await click(page, center); expect(await current(page)).toEqual(previous); await expect(panel).toBeVisible();
  const hash = await page.getByTestId('map-hash').textContent();
  await page.getByLabel('保存选项', { exact: true }).click(); await page.getByRole('button', { name: '仅保存浏览器恢复', exact: true }).click(); await checkpoint(page, hash!);
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(panel).toBeVisible();
  await click(page, center); await page.keyboard.press('Control+s'); await browserSaved(page);
  await expect(page.getByRole('dialog', { name: '未应用输入保护', exact: true })).toHaveCount(0); await expect(panel).toBeVisible(); expect(await current(page)).toEqual(previous);
  await page.screenshot({ path: info.outputPath('01-three-continuous-entrances.png') });
  await page.keyboard.press('Escape'); await expect(panel).toHaveCount(0); expect(await current(page)).toEqual(previous);
  await page.getByRole('button', { name: '添加入口', exact: true }).last().click(); await expect(panel).toBeVisible();
  await click(page, center); await page.keyboard.press('Enter'); await expect(panel).toHaveCount(0); expect(await current(page)).toEqual(previous);
  await page.getByRole('button', { name: '添加入口', exact: true }).last().click(); await panel.getByRole('button', { name: '完成添加入口', exact: true }).click();
  await expect(panel).toHaveCount(0); expect(await current(page)).toEqual(previous);
  await page.getByRole('button', { name: '添加入口', exact: true }).last().click(); await page.getByRole('button', { name: '道路', exact: true }).click();
  await expect(panel).toHaveCount(0); await page.getByRole('button', { name: '选择', exact: true }).click(); expect(await current(page)).toEqual(previous);
  await page.getByRole('button', { name: '添加入口', exact: true }).last().click(); await page.getByTestId('facilities-item-' + secondId).click();
  await expect(panel).toHaveCount(0); await expect(page.getByRole('dialog')).toHaveCount(0); expect(await current(page)).toEqual(previous);
  await page.getByRole('button', { name: '添加入口', exact: true }).last().click();
  await panel.getByRole('button', { name: '单个入口与接路设置', exact: true }).click();
  const single = page.getByRole('dialog', { name: '添加入口', exact: true });
  await expect(single).toBeVisible(); await expect(panel).toHaveCount(0);
  await single.getByLabel('名称', { exact: true }).fill('单点候选保留');
  await single.getByRole('button', { name: '在画布放置入口', exact: true }).click();
  const secondRing = previous.facilities[secondId]!.boundary.outer;
  await click(page, [secondRing[0][0], (secondRing[0][1] + secondRing[2][1]) / 2, 0]);
  await expect(single).toBeVisible(); const candidateText = await single.textContent();
  expect(await current(page)).toEqual(previous); await page.keyboard.press('Control+s');
  const saveGuard = page.getByRole('dialog', { name: '有未应用输入', exact: true });
  await expect(saveGuard).toBeVisible(); await saveGuard.getByRole('button', { name: '取消，保留输入', exact: true }).click();
  await expect(saveGuard).toHaveCount(0); await expect(single.getByLabel('名称', { exact: true })).toHaveValue('单点候选保留');
  expect(await single.textContent()).toBe(candidateText); expect(await current(page)).toEqual(previous);
  await single.getByRole('button', { name: '取消', exact: true }).click(); await expect(single).toHaveCount(0); expect(await current(page)).toEqual(previous);
  await page.reload(); await browserSaved(page); await expect(page.getByTestId('background-render-state')).toHaveAttribute('data-loaded', '1');
  expect(await current(page)).toEqual(previous); await expect(panel).toHaveCount(0);
  expect(await readGA01Target(GA01_TARGETS.find(target => target.id === 'cimc_v02')!)).toEqual(original);
  expect(createHash('sha256').update(await readFile(imagePath)).digest('hex')).toBe(imageSHA); expect(errors).toEqual([]);
  await writeFile(info.outputPath('continuous-entrances-evidence.json'), JSON.stringify({ browser: browser.version(), imageSHA, mapHash: hash, facilityId, positions, initialFacilitySelections: 1, immediatePoints: 3, nativeDoubleClickCreatesOnce: true, duplicateAndInvalidClicksUnchanged: true, separateUndoRedo: true, saveDuringContinuousMode: true, singlePointCandidateStillProtected: true, exits: ['Escape', 'Enter', 'done', 'tool', 'selectedObject'], restored: true }, null, 2));
});

test('real CIMC undoing a continuously edited building exits internal mode and permits drawing again', async ({ page }, info) => {
  test.setTimeout(120000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const original = await readGA01Target(GA01_TARGETS.find(target => target.id === 'cimc_v02')!);
  const map = structuredClone(original); map.mapId = 'MAP_CIMC_CONTINUOUS_OWNER_UNDO'; map.metadata.name = 'CIMC 真实底图撤销所属建筑验收副本';
  for (const key of ['nodes', 'roads', 'junctions', 'movements', 'facilities', 'zones', 'accessPoints', 'servicePoints', 'resources', 'extensions', 'extensionNamespaces', 'assets', 'backgroundLayers'] as const) (map as unknown as Record<string, unknown>)[key] = {};
  const imagePath = resolve('.cache/BG01/calibrated-cimc/background.jpg');
  expect(createHash('sha256').update(await readFile(imagePath)).digest('hex')).toBe('8ec6e74a72c9757f7113a440832dc9d9166518fe7f9da75979629a2cdb2ef713');
  await readyWorkbench(page); await importMapUI(page, map);
  await page.getByRole('button', { name: '底图', exact: true }).click();
  await page.getByTestId('background-file-input').setInputFiles([imagePath, resolve('.cache/BG01/calibrated-cimc/calibration.json')]);
  await expect(page.getByTestId('background-calibration-status')).toContainText('校准匹配');
  await page.getByRole('button', { name: '添加此底图', exact: true }).click();
  await expect(page.getByTestId('background-render-state')).toHaveAttribute('data-loaded', '1');
  await page.getByRole('button', { name: '适应底图', exact: true }).click();
  await page.locator('summary').filter({ hasText: /^底图显示与调整$/ }).click();
  await page.getByRole('button', { name: '收起属性面板', exact: true }).click();
  await page.getByLabel('建筑绘制形状', { exact: true }).selectOption('facilityRect');
  await page.getByRole('button', { name: '保留原图并升级', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  const base = await current(page);
  await click(page, [400, 1020, 0]); await click(page, [470, 1080, 0]);
  const drawn = await current(page), facilityId = Object.keys(drawn.facilities)[0]!, ring = drawn.facilities[facilityId]!.boundary.outer;
  expect(Object.keys(drawn.facilities)).toHaveLength(1);
  await page.getByRole('button', { name: '选择', exact: true }).click(); await page.getByTestId('facilities-item-' + facilityId).click();
  await page.getByRole('button', { name: '编辑内部', exact: true }).click();
  const internalExit = page.getByRole('button', { name: '退出内部编辑', exact: true }); await expect(internalExit).toBeVisible();
  await openDrawingSettings(page);
  const globalEntrance = page.locator('details').filter({ has: page.locator(':scope > summary').filter({ hasText: /^绘图与显示设置$/ }) }).getByRole('button', { name: '添加入口', exact: true });
  await expect(globalEntrance).toBeEnabled(); await globalEntrance.click();
  const panel = page.getByRole('complementary', { name: '连续添加入口', exact: true }); await expect(panel).toBeVisible();
  await click(page, [ring[0][0], (ring[0][1] + ring[2][1]) / 2, 0]);
  const placed = await current(page); expect(Object.keys(placed.accessPoints)).toHaveLength(1); expect(Object.keys(placed.nodes)).toHaveLength(1); expect(placed.roads).toEqual(base.roads);
  await page.keyboard.press('Control+z'); expect(await current(page)).toEqual(drawn);
  await expect(panel).toBeVisible(); await expect(panel).toContainText('当前入口数：0'); await expect(internalExit).toBeVisible();
  await page.keyboard.press('Control+z'); expect(await current(page)).toEqual(base);
  await expect(panel).toHaveCount(0); await expect(internalExit).toHaveCount(0); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByLabel('建筑绘制形状', { exact: true }).selectOption('facilityRect');
  await click(page, [ring[0][0] + 10, ring[0][1] + 10, 0]); await click(page, [ring[0][0] + 45, ring[0][1] + 35, 0]);
  const redrawn = await current(page), replacementId = Object.keys(redrawn.facilities)[0]!;
  expect(Object.keys(redrawn.facilities)).toHaveLength(1);
  // Quick tracing reuses the first free ID after undo; the newly drawn geometry must replace the old outline.
  expect(redrawn.facilities[replacementId]!.boundary).not.toEqual(drawn.facilities[facilityId]!.boundary);
  expect(redrawn.facilities[replacementId]!.accessPointIds).toEqual([]);
  expect(redrawn.revision).toBe(base.revision + 1); expect(redrawn.nodes).toEqual(base.nodes); expect(redrawn.accessPoints).toEqual(base.accessPoints); expect(redrawn.roads).toEqual(base.roads);
  await page.getByRole('button', { name: '选择', exact: true }).click(); await page.getByTestId('facilities-item-' + replacementId).click();
  await expect(page.getByRole('button', { name: '编辑内部', exact: true })).toBeEnabled(); await expect(internalExit).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('02-owner-undo-drawing-resumed.png') });
  expect(await readGA01Target(GA01_TARGETS.find(target => target.id === 'cimc_v02')!)).toEqual(original); expect(errors).toEqual([]);
});