import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { expect, test } from '@playwright/test';
import type { YardMap } from '../../src/domain/model';
import { inspectServiceConnection } from '../../src/topology/serviceConnections';
import { browserSaved, checkpoint, expectVisiblePosition, exportMapUI, importMapUI, readyWorkbench, selectResult } from '../helpers/RF01_workbench';
import { drawingControl, saveToBrowser } from '../helpers/workbenchUi';

test('EA01 separates the real HW099 entrance, then moves its entrance and yard without moving public roads', async ({ page }, info) => {
  test.setTimeout(240000);
  const sourcePath = resolve(process.env.UX02_MQ01_ROOT ?? '../../projects/MQ01_Repair_20260913', 'hanwha/map.json');
  let bytes: Buffer;
  try { bytes = await readFile(sourcePath); } catch (cause) { throw new Error('blocked_input: required Hanwha map missing: ' + sourcePath, { cause }); }
  const sha = (value: Buffer) => createHash('sha256').update(value).digest('hex');
  const sourceSHA = sha(bytes);
  expect(sourceSHA, 'blocked_input: frozen Hanwha SHA').toBe('026bf0c409b151aa005fe59d50e0aeda294eca83a5fbccf9b5927b9190cb4749');
  const original = JSON.parse(bytes.toString('utf8')) as YardMap;
  const originalNode = original.accessPoints.AP_HW099!.nodeId;
  const publicRoads = Object.fromEntries(Object.entries(original.roads).filter(([, road]) => !(road.extensions?.['sr02.planning'] as { ownerEntityId?: string } | undefined)?.ownerEntityId));
  const bundles = new Set<string>();
  page.on('response', response => { if (/\/assets\/[^/]+\.js$/.test(new URL(response.url()).pathname)) bundles.add(response.url()); });
  await readyWorkbench(page); await importMapUI(page, original, bytes);
  await (await drawingControl(page, '网格吸附')).selectOption('1');
  await (await drawingControl(page, '节点吸附')).uncheck();
  await selectResult(page, 'accessPoints', 'AP_HW099');
  await page.getByRole('button', { name: '定位 AP_HW099', exact: true }).click();
  const originalHash = (await page.getByTestId('map-hash').textContent())!;
  const start = page.getByRole('button', { name: '建立独立入口并保留接路', exact: true });
  await start.click();
  const separationDistance = Number(await page.getByLabel('独立入口距离', { exact: true }).inputValue());
  expect(separationDistance).toBeGreaterThan(7); // HW099 main-road declared half-width is 7m.
  expect(separationDistance).toBeLessThan(8); // Stay on the existing 8m route and keep both segments nonzero.
  const entranceX = 2020 - separationDistance;
  await page.screenshot({ path: info.outputPath('ea01-proposal.png'), fullPage: true });
  await page.getByLabel('独立入口距离', { exact: true }).fill('0');
  await expect(page.getByRole('button', { name: '确认建立独立入口', exact: true })).toBeDisabled();
  await expect(page.getByTestId('map-hash')).toHaveText(originalHash);
  await page.getByLabel('独立入口距离', { exact: true }).press('Escape');
  await expect(page.getByLabel('独立入口距离', { exact: true })).toHaveCount(0);
  await expect(page.locator('.canvas-status')).toContainText('0 个撤销事务');
  const roadLock = page.getByTestId('layer-locked-roads');
  if (!await roadLock.isVisible()) await page.locator('summary').filter({ hasText: /^基础图层与标签$/ }).click();
  await roadLock.check();
  await start.click();
  await page.getByRole('button', { name: '确认建立独立入口', exact: true }).click();
  await expect(page.locator('.canvas-context [role="alert"]')).toContainText('已锁定');
  await expect(page.getByTestId('map-hash')).toHaveText(originalHash);
  await expect(page.locator('.canvas-status')).toContainText('0 个撤销事务');
  await page.getByRole('button', { name: '取消独立入口', exact: true }).click();
  await roadLock.uncheck();
  await start.click();
  await page.getByRole('button', { name: '确认建立独立入口', exact: true }).click();
  await expect(page.getByTestId('map-hash')).not.toHaveText(originalHash);
  const separated = (await exportMapUI(page, info, 'separated')).map;
  const newNode = separated.accessPoints.AP_HW099!.nodeId;
  expect(newNode).not.toBe(originalNode);
  expect(separated.nodes[newNode]!.position).toEqual([entranceX, 2192.2, 0]);
  expect(separated.coordinateFrame).toEqual(original.coordinateFrame);
  expect(separated.facilities).toEqual(original.facilities);
  expect(separated.resources).toEqual(original.resources);
  expect(separated.nodes[originalNode]).toEqual(original.nodes[originalNode]);
  for (const [id, road] of Object.entries(publicRoads)) expect(separated.roads[id]).toEqual(road);
  expect(inspectServiceConnection(separated, 'SP_HW099').internalPathStatus).toBe('continuous');
  expect(Object.keys(separated.roads)).toHaveLength(Object.keys(original.roads).length + 1);
  await expect(page.locator('.canvas-status')).toContainText('1 个撤销事务');
  const separatedHash = (await page.getByTestId('map-hash').textContent())!;
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  await expect(page.getByTestId('map-hash')).toHaveText(originalHash);
  expect((await exportMapUI(page, info, 'undo-separation')).map).toEqual(original);
  await page.getByRole('button', { name: '重做', exact: true }).click();
  await expect(page.getByTestId('map-hash')).toHaveText(separatedHash);
  expect((await exportMapUI(page, info, 'redo-separation')).map).toEqual(separated);
  async function drag(from: [number, number, number], to: [number, number, number]) {
    const a = await expectVisiblePosition(page, from), b = await expectVisiblePosition(page, to);
    await page.mouse.move(a.x, a.y); await page.mouse.down(); await page.mouse.move(b.x, b.y, { steps: 12 }); await page.mouse.up();
  }
  await selectResult(page, 'accessPoints', 'AP_HW099');
  await page.getByRole('button', { name: '定位 AP_HW099', exact: true }).click();
  await drag([entranceX, 2192.2, 0], [2013, 2194, 0]);
  await expect(page.getByTestId('map-hash')).not.toHaveText(separatedHash);
  const movedPoint = (await exportMapUI(page, info, 'moved-entrance')).map;
  expect(movedPoint.nodes[newNode]!.position).toEqual([2013, 2194, 0]);
  expect(movedPoint.nodes[originalNode]).toEqual(original.nodes[originalNode]);
  expect(movedPoint.facilities).toEqual(separated.facilities);
  expect(movedPoint.resources).toEqual(separated.resources);
  await expect(page.locator('.canvas-status')).toContainText('2 个撤销事务');
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  await expect(page.getByTestId('map-hash')).toHaveText(separatedHash);
  await selectResult(page, 'facilities', 'F_HW099');
  await page.getByRole('button', { name: '定位 F_HW099', exact: true }).click();
  await drag([2035, 2100, 0], [2055, 2100, 0]);
  await expect(page.getByTestId('map-hash')).not.toHaveText(separatedHash);
  const moved = (await exportMapUI(page, info, 'moved-yard')).map;
  expect(moved.nodes[newNode]!.position).toEqual([entranceX + 20, 2192.2, 0]);
  expect(moved.nodes.N_HW_3bbc98ef77!.position).toEqual([2032, 2192.2, 0]);
  expect(moved.facilities.F_HW099!.boundary.outer).toEqual(separated.facilities.F_HW099!.boundary.outer.map(p => [p[0] + 20, p[1], p[2]]));
  expect(moved.coordinateFrame).toEqual(original.coordinateFrame);
  expect(moved.nodes[originalNode]).toEqual(original.nodes[originalNode]);
  expect(moved.resources).toEqual(separated.resources);
  expect(moved.movements).toEqual(separated.movements);
  expect(moved.servicePoints).toEqual(separated.servicePoints);
  for (const [id, road] of Object.entries(publicRoads)) expect(moved.roads[id]).toEqual(road);
  expect(inspectServiceConnection(moved, 'SP_HW099').internalPathStatus).toBe('continuous');
  await expect(page.locator('.canvas-status')).toContainText('2 个撤销事务');
  const movedHash = (await page.getByTestId('map-hash').textContent())!;
  await page.screenshot({ path: info.outputPath('ea01-yard-moved.png'), fullPage: true });
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  await expect(page.getByTestId('map-hash')).toHaveText(separatedHash);
  await page.getByRole('button', { name: '重做', exact: true }).click();
  await expect(page.getByTestId('map-hash')).toHaveText(movedHash);
  expect((await exportMapUI(page, info, 'redo-yard')).map).toEqual(moved);
  await saveToBrowser(page); await checkpoint(page, movedHash); await browserSaved(page);
  await page.reload(); await browserSaved(page);
  await expect(page.getByTestId('map-hash')).toHaveText(movedHash);
  expect((await exportMapUI(page, info, 'refreshed')).map).toEqual(moved);
  await importMapUI(page, moved);
  expect((await exportMapUI(page, info, 'roundtrip')).map).toEqual(moved);
  expect(sha(await readFile(sourcePath))).toBe(sourceSHA);
  const receipt = { sourcePath, sourceSHA, originalHash, separatedHash, movedHash, newNode, separationDistance, entranceOutsideDeclaredMainBand: true, bundles: [...bundles],
    previewCancelNoCommit: true, zeroDistanceRejected: true, lockedDependentRoadRefused: true, privateEntranceDrag: true, yard20mDrag: true,
    publicNetworkUnchanged: true, capacityUnchanged: true, coordinateFrameUnchanged: true, undoRedoStableIDs: true,
    serviceInternalPathContinuous: true, savedRefreshed: true, jsonRoundtrip: true, originalUnchanged: true,
    boundary: 'Static editing and declared connectivity only; changed turning geometry is not a vehicle clearance certification.' };
  await writeFile(info.outputPath('receipt.json'), JSON.stringify(receipt, null, 2));
});
