import { expect, test, type Page } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { SPATIAL_CLASSIFICATION_NAMESPACE } from '../../src/domain/spatialClassification';
import type { YardMap } from '../../src/domain/model';
import { readGA01Target } from '../helpers/GA01_targets';
import { browserSaved, checkpoint, exportMapUI, importMapUI, storedWorkspace } from '../helpers/RF01_workbench';
import { openDrawingSettings } from '../helpers/workbenchUi';
import { canvasClick, chooseSpatial, classificationBackground, savedMap, unchangedNetwork, undoRedoMap } from '../helpers/classificationWorkbench';

test.use({ viewport: { width: 1920, height: 1080 } });
async function classesPanel(page: Page) {
  await openDrawingSettings(page);
  const summary = page.locator('summary').filter({ hasText: /^建筑与区域分类$/ });
  if (!await summary.evaluate(element => (element.parentElement as HTMLDetailsElement).open)) await summary.click();
}
const apply = (page: Page) => page.getByRole('button', { name: '应用属性', exact: true }).click();
const annotation = (map: YardMap, kind: 'facilities' | 'zones', id: string) => map[kind][id]!.extensions?.[SPATIAL_CLASSIFICATION_NAMESPACE] as { classId: string; depthM?: { state: string; value?: number; sourceRef?: string }; depthReference?: string };

test('real background dry dock is a zone with sourced depth, separate from building height and road geometry', async ({ page }, info) => {
  test.setTimeout(180000); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const { baseline, original, target, imageSHA } = await classificationBackground(page, 'DOCK');
  await page.getByLabel('区域绘制形状', { exact: true }).selectOption('zoneRect');
  await canvasClick(page, [320, 930, 0]); await canvasClick(page, [380, 990, 0]);
  const drawn = await savedMap(page), id = Object.keys(drawn.zones).find(id => !baseline.zones[id])!;
  expect(id).toBeTruthy(); await chooseSpatial(page, 'zones', id);
  const category = page.getByLabel('区域分类', { exact: true });
  await expect(category).toBeVisible(); await expect(page.getByLabel('区域类型', { exact: true })).toBeHidden();
  await expect(category.locator('option[value="dry_dock"]')).toHaveCount(1);
  await page.getByLabel('名称', { exact: true }).fill('干船坞深度设计假设验收');
  await category.selectOption('dry_dock');
  await expect(page.getByLabel('干船坞深度 (m)', { exact: true })).toHaveValue('');
  await page.getByLabel('干船坞深度 (m)', { exact: true }).fill('9.5');
  await page.getByLabel('深度参照面', { exact: true }).fill('验收假设：从坞口地坪向下至坞底');
  await apply(page);
  const classified = await savedMap(page); expect(classified.revision).toBe(drawn.revision + 1);
  const value = annotation(classified, 'zones', id);
  expect(value.classId).toBe('dry_dock'); expect(value.depthM).toMatchObject({ state: 'known', value: 9.5 });
  expect(classified.sources[value.depthM!.sourceRef!]!.category).toBe('design_assumption');
  expect(value.depthReference).toBe('验收假设：从坞口地坪向下至坞底');
  expect(classified.zones[id]!.passability).toBe('unknown'); unchangedNetwork(drawn, classified);
  expect(classified.facilities).toEqual(drawn.facilities); await undoRedoMap(page, drawn, classified);
  await page.getByLabel('干船坞深度 (m)', { exact: true }).fill('-2'); await apply(page);
  await expect(page.locator('.spatial-property [role="alert"]')).toBeVisible(); expect(await savedMap(page)).toEqual(classified);
  await page.getByLabel('干船坞深度 (m)', { exact: true }).fill(''); await apply(page);
  const unknown = await savedMap(page); expect(annotation(unknown, 'zones', id).depthM?.state).toBe('unknown');
  unchangedNetwork(classified, unknown); await undoRedoMap(page, classified, unknown);
  await page.getByRole('button', { name: '撤销', exact: true }).click(); expect(await savedMap(page)).toEqual(classified);
  const hash = await page.getByTestId('map-hash').textContent();
  await page.getByLabel('保存选项', { exact: true }).click(); await page.getByRole('button', { name: '仅保存浏览器恢复', exact: true }).click(); await checkpoint(page, hash!);
  expect((await exportMapUI(page, info, 'classified-dry-dock')).map).toEqual(classified);
  await page.getByLabel('名称', { exact: true }).scrollIntoViewIfNeeded();
  await expect(page.getByLabel('干船坞深度 (m)', { exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath('dry-dock-depth.png') });
  await page.reload(); await browserSaved(page); expect(await savedMap(page)).toEqual(classified);
  await expect(page.getByTestId('background-render-state')).toHaveAttribute('data-loaded', '1');
  expect(await readGA01Target(target)).toEqual(original); expect(errors).toEqual([]);
  await writeFile(info.outputPath('classification-evidence.json'), JSON.stringify({ imageSHA, hash, zoneId: id, depthIsDesignAssumption: true, unchangedGeometryAndReferences: true, undoRedo: true, exportReload: true }, null, 2));
});

test('real editor separates building and area custom classes, drawing defaults and renames survive JSON roundtrip', async ({ page }, info) => {
  test.setTimeout(240000); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const { baseline, original, target } = await classificationBackground(page, 'CLASSES');
  await chooseSpatial(page, 'facilities', 'F_CR002');
  const building = page.getByLabel('建筑分类', { exact: true });
  await expect(building).toBeVisible(); await expect(page.getByLabel('设施类型', { exact: true })).toBeHidden();
  await expect(building.locator('option[value="dry_dock"]')).toHaveCount(0);
  await expect(building.locator('option[value="yard"]')).toHaveCount(0);
  await expect(page.getByLabel('干船坞深度 (m)', { exact: true })).toHaveCount(0);
  await expect(page.getByLabel('设施类型', { exact: true }).locator('option[value="yard"]')).toHaveCount(0);
  await classesPanel(page); await page.getByRole('button', { name: '管理自定义分类', exact: true }).click();
  await page.getByLabel('自定义分类名称', { exact: true }).fill('精密加工厂房');
  await page.getByLabel('自定义分类适用对象', { exact: true }).selectOption('facilities');
  await expect(page.getByLabel('自定义分类适用对象', { exact: true }).locator('option[value="both"]')).toHaveCount(0);
  await page.getByRole('button', { name: '新增自定义分类', exact: true }).click();
  const withBuildingClass = await savedMap(page); await undoRedoMap(page, baseline, withBuildingClass);
  await classesPanel(page); await page.getByRole('button', { name: '管理自定义分类', exact: true }).click();
  await page.getByLabel('自定义分类名称', { exact: true }).fill('分段待运堆场');
  await page.getByLabel('自定义分类适用对象', { exact: true }).selectOption('zones');
  await page.getByRole('button', { name: '新增自定义分类', exact: true }).click();
  const withClasses = await savedMap(page); unchangedNetwork(baseline, withClasses);
  const buildingDefault = page.getByLabel('新建筑分类', { exact: true }), zoneDefault = page.getByLabel('新区域分类', { exact: true });
  await expect(buildingDefault.locator('option').filter({ hasText: '分段待运堆场' })).toHaveCount(0);
  await expect(zoneDefault.locator('option').filter({ hasText: '精密加工厂房' })).toHaveCount(0);
  await buildingDefault.selectOption({ label: '精密加工厂房' }); const buildingClassId = await buildingDefault.inputValue();
  await zoneDefault.selectOption({ label: '分段待运堆场' }); const zoneClassId = await zoneDefault.inputValue();
  expect(await savedMap(page)).toEqual(withClasses); // Drawing preferences do not change declared map data.
  await page.getByRole('button', { name: '收起属性面板', exact: true }).click();
  await page.getByRole('button', { name: '适应地图', exact: true }).click();
  await page.getByLabel('建筑绘制形状', { exact: true }).selectOption('facilityRect');
  await canvasClick(page, [320, 930, 0]); await canvasClick(page, [380, 990, 0]);
  const drawnBuilding = await savedMap(page), facilityId = Object.keys(drawnBuilding.facilities).find(id => !withClasses.facilities[id])!;
  expect(annotation(drawnBuilding, 'facilities', facilityId).classId).toBe(buildingClassId);
  expect(drawnBuilding.facilities[facilityId]!.kind).toBe('building'); await undoRedoMap(page, withClasses, drawnBuilding);
  await page.getByLabel('区域绘制形状', { exact: true }).selectOption('zoneRect');
  await canvasClick(page, [400, 930, 0]); await canvasClick(page, [460, 990, 0]);
  const drawnZone = await savedMap(page), zoneId = Object.keys(drawnZone.zones).find(id => !drawnBuilding.zones[id])!;
  expect(annotation(drawnZone, 'zones', zoneId).classId).toBe(zoneClassId);
  expect(drawnZone.zones[zoneId]!.passability).toBe('unknown'); await undoRedoMap(page, drawnBuilding, drawnZone);
  await classesPanel(page); await page.getByRole('button', { name: '管理自定义分类', exact: true }).click(); await page.getByLabel('待改名分类', { exact: true }).selectOption(buildingClassId);
  await page.getByLabel('分类新名称', { exact: true }).fill('精密加工车间');
  await page.getByRole('button', { name: '保存分类名称', exact: true }).click();
  const renamed = await savedMap(page); expect(annotation(renamed, 'facilities', facilityId).classId).toBe(buildingClassId);
  expect(renamed.facilities).toEqual(drawnZone.facilities); expect(renamed.zones).toEqual(drawnZone.zones);
  await undoRedoMap(page, drawnZone, renamed); unchangedNetwork(baseline, renamed);
  const exported = await exportMapUI(page, info, 'custom-building-area-classes'); expect(exported.map).toEqual(renamed);
  await page.reload(); await browserSaved(page); expect(await savedMap(page)).toEqual(renamed);
  expect((await storedWorkspace(page)).editor?.drawing).toMatchObject({ facilityClassificationId: buildingClassId, zoneClassificationId: zoneClassId });
  await importMapUI(page, exported.map); expect(await savedMap(page)).toEqual(renamed);
  await chooseSpatial(page, 'facilities', facilityId); await expect(page.getByLabel('建筑分类', { exact: true })).toHaveValue(buildingClassId);
  await expect(page.getByLabel('建筑分类', { exact: true }).locator('option:checked')).toHaveText('精密加工车间');
  await chooseSpatial(page, 'facilities', 'F_CR009');
  await expect(page.locator('.entity-kind')).toHaveText('历史设施边界');
  await expect(page.getByLabel('设施类型', { exact: true })).toHaveValue('yard');
  expect(await savedMap(page)).toEqual(renamed);
  await chooseSpatial(page, 'facilities', facilityId); await page.getByLabel('名称', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('separate-building-area-classes.png') });
  expect(await readGA01Target(target)).toEqual(original); expect(errors).toEqual([]);
});
